%--------------------------------------------------------------------------
% Model 'Fujita_SciSignal2010' from the benchmarks collection
%--------------------------------------------------------------------------
clear all;

% 9 states:
syms EGFR pEGFR pEGFR_Akt Akt pAkt S6 pAkt_S6 pS6 EGF_EGFR
x = [EGFR pEGFR pEGFR_Akt Akt pAkt S6 pAkt_S6 pS6 EGF_EGFR].';

% 16 parameters:
syms scaleFactor_pEGFR...
    scaleFactor_pAkt...
    scaleFactor_pS6...
    EGFR_turnover... 
    reaction_1_k1...
    reaction_1_k2...
    reaction_2_k1...
    reaction_2_k2...
    reaction_3_k1...
    reaction_4_k1...
    reaction_5_k1...
    reaction_5_k2...
    reaction_6_k1...
    reaction_7_k1...
    reaction_8_k1...
    reaction_9_k1
p = [scaleFactor_pEGFR...
    scaleFactor_pAkt...
    scaleFactor_pS6...
    EGFR_turnover... 
    reaction_1_k1...
    reaction_1_k2...
    reaction_2_k1...
    reaction_2_k2...
    reaction_3_k1...
    reaction_4_k1...
    reaction_5_k1...
    reaction_5_k2...
    reaction_6_k1...
    reaction_7_k1...
    reaction_8_k1...
    reaction_9_k1].';

% 3 outputs:
h = [ 
    scaleFactor_pEGFR*(pEGFR + pEGFR_Akt);
    scaleFactor_pAkt*(pAkt + pAkt_S6);
    pS6*scaleFactor_pS6
    ];

% 1 known inputs:
syms EGF_u
u = EGF_u;
% 0 unknown inputs:
w = [];

% dynamic equations:
f = [ 
68190.0*EGFR_turnover - EGF_u*EGFR*reaction_1_k1 + EGF_EGFR*reaction_1_k2 - EGFR*EGFR_turnover;
EGF_EGFR*reaction_9_k1 - pEGFR*reaction_4_k1 + pEGFR_Akt*reaction_2_k2 + pEGFR_Akt*reaction_3_k1 - Akt*pEGFR*reaction_2_k1;
Akt*pEGFR*reaction_2_k1 - pEGFR_Akt*reaction_3_k1 - pEGFR_Akt*reaction_2_k2;
pAkt*reaction_7_k1 + pEGFR_Akt*reaction_2_k2 - Akt*pEGFR*reaction_2_k1;
pAkt_S6*reaction_5_k2 - pAkt*reaction_7_k1 + pAkt_S6*reaction_6_k1 + pEGFR_Akt*reaction_3_k1 - S6*pAkt*reaction_5_k1;
pAkt_S6*reaction_5_k2 + pS6*reaction_8_k1 - S6*pAkt*reaction_5_k1;
S6*pAkt*reaction_5_k1 - pAkt_S6*reaction_6_k1 - pAkt_S6*reaction_5_k2;
pAkt_S6*reaction_6_k1 - pS6*reaction_8_k1;
EGF_u*EGFR*reaction_1_k1 - EGF_EGFR*reaction_1_k2 - EGF_EGFR*reaction_9_k1
];

% initial conditions:
ics  = [1,0,0,1,0,1,0,0,0];   
% which initial conditions may be replaced with their known values:
known_ics = [0,1,1,0,1,0,1,1,1]; 

save('Fujita','x','p','u','w','h','f','ics','known_ics');

